name: Infracost Analyzer

on:
  workflow_dispatch:

jobs:
  build:
    name: Infracost
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source code so we can install the action locally
        uses: actions/checkout@v3
      - name: Setup Infracost
        uses: ./setup
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
      - name: Checkout base branch
        uses: actions/checkout@v3
        with: {}
      - name: Generate Infracost cost estimate baseline
        run: |
          infracost breakdown --path=. --show-skipped --terraform-var-file dev.tfvars \
                              --format=json \
                              --out-file=/tmp/infracost-base.json
