name:  pipeline destroy - homologacao

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
    terraform:
        name: Destroy Homologacao (CD)
        runs-on: ubuntu-latest
        env:
           TF_WORKING_DIR: '.'

        defaults:
            run:
                shell: bash
                working-directory: ${{ env.TF_WORKING_DIR }}

        steps:
          - name: Checkout
            uses: actions/checkout@v2
        
          - name: Setup Terraform
            uses: hashicorp/setup-terraform@v1
            with:
              terraform_version: 1.2.1
        
          - name: Terraform Init
            id: init
            run: terraform init -backend=true -backend-config="config/hml/backend.hcl" -backend-config="access_key=${{ env.AWS_ACCESS_KEY_ID }}" -backend-config="secret_key=${{ env.AWS_SECRET_ACCESS_KEY }}"
        
          - name: Terraform Validate
            id: validate
            run: terraform validate -no-color
        
          - name: Terraform Destroy
            run: terraform destroy -auto-approve -var-file="config/hml/terraform.tfvars"